### ISSUE TITLE
Option to *not* do git pull

### ISSUE THREAD

**Issue by RemiLehe** [AMReX-Codes/regression_testing#11]
Thanks for developing these tools!

I would like to use them to do automated testing (on a remote server) for an AMReX-based code (WarpX).
Due to the particular configuration of the remote server and Docker containers that I use there, I can easily download the latest branch of WarpX locally, but then when the python script `regtest.py` tries to do "git pull" for warpx, this fails due to insufficient permissions (the repository is private).

Therefore, I was wondering whether it would be possible to modify the `regtest.py` to avoid pulling the code. One possibility, from the user's point of view, would be to do 
```
[AMReX]
dir = /path/to/amrex/
branch = development

[source]
dir = /path/to/warpx
branch = master
do_git_pull = false
``` 
Would you agree with the above interface? If yes, I can try to do a PR for this.

**Comment by zingale** [comment]
does the option `--no_update all` do what you need?

**Comment by RemiLehe** [comment]
Yes! That works! Sorry for missing this.

Should I close the issue?

**Comment by zingale** [comment]
no problem.  

sure go ahead and close this.
