### ISSUE TITLE
Add flag that disable comparison with benchmarks

### ISSUE THREAD

**Issue by RemiLehe** [AMReX-Codes/regression_testing#12]
I was wondering if it would be possible to add a flag (e.g. `--skip_comparison`) to `regtests.py` which would skip the comparison with the benchmarks.

This may seem odd, since `regtest.py` performs (primarily) regression tests. However, (at least to me) it is also a convenient way to compile all the tests and run the associated python checker script (defined by `analysisRoutine = `), without necessarily requiring machine-precision comparisons with benchmarks. 

This would be particularly useful when setting up automated tests on remote servers (Travis-style) where getting the reference data on the remote server might not be very convenient.

**Comment by zingale** [comment]
yeah, that's something we can add.  Things are hectic right now, but in June I am freed up and plan to work on the test suite some then.

**Comment by RemiLehe** [comment]
I would be happy to try to do a PR on this, if that can save you some time. Would that work?

**Comment by atmyers** [comment]
I added a "doComparison" option recently that you can toggle in the `.ini` file on a test-by-test basis. There isn't a flag to turn that on globally, but you maybe you could have the flag turn that on for all the tests?

**Comment by RemiLehe** [comment]
Thanks @atmyers ! I'll look into this.
