### ISSUE TITLE
does this work with CMake app builds?

### ISSUE THREAD

**Issue by BenWibking** [AMReX-Codes/regression_testing#138]
I am trying to get this working with Quokka, but the CMake support seems to be hard-coded for AMReX.

Does this work for apps built with CMake? If not, what functions do I need to change to get it working?

**Comment by zingale** [comment]
It should work. i believe that warpx uses it.

**Comment by BenWibking** [comment]
Ah ok, it basically works. There are just a few parameters that aren't passed to CMake configure, unlike the Makefile builds. Making a PR now...

**Comment by zingale** [comment]
great!
