### ISSUE TITLE
suite report issues

### ISSUE THREAD

**Issue by AnneFelden** [AMReX-Codes/regression_testing#23]
With the most recent commit (59e95cb3be6c96a6899e8c6) the suite report seems to crash on unbutu. It seems to work with commit 813bd4ce698bb.

**Comment by zingale** [comment]
@KiranEiden can you look at this?

**Comment by KiranEiden** [comment]
@AnneFelden @zingale Alright, sorry about that. This should be fixed once the latest pull request is merged. Let me know if there are any other issues.
