### ISSUE TITLE
AMReX tools fail to build

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/regression_testing#51]
This is probably more of an AMReX issue, but I thought I would start here. The past two days I have seen this in my logs and my tests fail to run:
```
   building particle_compare...
   make -j24 AMREX_HOME=/path/to/pelec-testing/amrex/   DEBUG=FALSE USE_MPI=FALSE  COMP=g++ TEST=TRUE USE_ASSERTION=TRUE 
   WARNING: build failed
   unable to continue, tools not able to be built
```

**Comment by zingale** [comment]
yes, I've had that too.  I don't know what changed in AMReX that is causing this.  If I do a `make realclean` manually in that directory and then rebuild, it seems to work.

**Comment by drummerdoc** [comment]
Yeah, that was going to be my immediate suggestion....`make realclean`

**Comment by jrood-nrel** [comment]
Thanks! Trying it now. I will just close this assuming it works and reopen if it doesn't.

**Comment by WeiqunZhang** [comment]
This is a known issue.  You can fix it by using the `battra` branch or manually fix it by making the following change.
```
- suite.py:            comp_string, rc = self.build_c(opts="DEBUG=FALSE USE_MPI=FALSE ")
+ suite.py:            comp_string, rc = self.build_c(opts="DEBUG=FALSE USE_MPI=FALSE EBASE=particle_compare ")
```

**Comment by WeiqunZhang** [comment]
The change is also in this pull-request. https://github.com/AMReX-Codes/regression_testing/pull/49/files

**Comment by zingale** [comment]
I'll review and merge that now
