### ISSUE TITLE
False Positives: Tests Should Fail if Build Fails

### ISSUE THREAD

**Issue by ax3l** [AMReX-Codes/regression_testing#87]
When build steps fail, e.g., for tools
```
building tools...
   building particle_compare...
   make -j2 AMREX_HOME=/tmp/ci-31YWhskdkz/amrex/   DEBUG=FALSE USE_MPI=FALSE  COMP=g++ TEST=TRUE USE_ASSERTION=TRUE WarpxBinDir= 
   WARNING: build failed
   unable to continue, tools not able to be built
Finishing: Build & test
```

Then the overall return status should be non-zero.
Otherwise, CI using the regression testing scripts silently passes (permanent false negative).

Seen today by @RemiLehe and @Ezoni on WarpX CI.

**Comment by WeiqunZhang** [comment]
https://github.com/AMReX-Codes/regression_testing/blob/main/suite.py#L1009

This particular issue was fixed 2 years ago.  But warpx's regression testing repo was not updated.
